import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import { ThemeProvider } from "styled-components";
import theme from "./theme";
import { StyledRoot } from "./styledRoot";
import AdminLayout from "./layout/adminLayout";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body

      >
        <AppRouterCacheProvider>
          <StyledRoot>
            {/* <AdminLayout> */}
            {children}
            {/* </AdminLayout> */}

          </StyledRoot>

        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
